#!/usr/bin/perl
# original from: http://hints.macworld.com/article.php?story=20050401212406724
$smburl = `pbpaste`;
$smburl =~ s"\n" "g;
if ($smburl =~ m"^\\\\([^\\]*)\\([^\\]*)\\(.*)") {
	my ($server, $share, $path) = ($1, $2, $3);
	$path =~ s"\s*$"";
	$path =~ s"\\"\/"g;
	$path =~ s"\s"\\ "g;
	system("echo /Volumes/$share/$path | pbcopy");
}