#!/bin/bash

#source: https://github.com/jenius/config/blob/master/.profile

git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative