#!/bin/bash

if [ "$1" = "?" ]
	then
		B1="\033[1m";
		B2="\033[0m";
		echo -e "";
		echo -e "${B1}AUTHOR${B2}";
		echo -e "  Marcelo Miranda Carneiro - mcarneiro@gmail.com";
		echo -e "";
		echo -e "${B1}INFO${B2} (release 2011-01-11)";
		echo -e "  removes all \"._\" files from the server (SVN) using the current working folder path as reference";
		echo -e "";
		echo -e "${B1}USAGE${B2}";
		echo -e "  svn-rm-mac-hidden MESSAGE";
		echo -e "";
		echo -e "${B1}REQUIRE${B2}";
		echo -e "  svn-url";
		echo -e "";
		exit 1;
fi


HAS_SVN_URL="$(type -t svn-url)";

if [ "$HAS_SVN_URL" = "" ];
	then echo "ERROR: \"svn-url\" command is required. Get it on \"http://gist.github.com/580966#file_svn_url\"";
	exit 1;
fi;
if [ "$1" = "" ];
	then echo "ERROR: Message is required.";
	exit 1;
fi;

FILE_LIST="$(for a in $(svn ls $(svn-url) --depth infinity | grep "\._"); do echo "$(svn-url)$a"; done;)";

if [ "$FILE_LIST" != "" ];
	then svn rm $FILE_LIST -m "$1";
	else echo "WARNING: Nothing to do.";
fi;